### ISSUE TITLE
Unable to use getRequests

### ISSUE THREAD

**Issue by riccardoroasio** [chmanie/webdriverajax#1]
Hi,

maybe is not an issue but i'm not able to use GetRequests.
While trying to use it in that way:

```javascript

var webdriverio = require('webdriverio');
var wdajax = require('webdriverajax');

wdajax.init(client);
 

client
    .init()
    .setViewportSize({width:1920,height:1080})
    .url('**myurl**')
   .setupInterceptor() // capture ajax calls 
    .waitForExist('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/div[1]/input',10000)
    .setValue('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/div[1]/input','yuser')
    .setValue('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/div[2]/input','mypassword')
    .click('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/input[5]')
    .pause(1000)
    .getRequests()
    .then(function(requests){console.log(requests);})
    .end();
```

it crashes with following error:

RuntimeError: window.__webdriverajax is undefined
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'probe_server-probe_server-2334910', ip: '172.17.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-c9', java.version: '1.7.0_79'
Driver info: driver.version: unknown 
    at execute(<Function>, ) - index.js:104:27

What I'm doing wrong?

Thanks,
Riccardo

**Comment by chmanie** [comment]
Hey, thanks for the bug report! I didn't particularly test the manual initialisation. I will do that and then come back to you.

Could you tell me what browser version and what version of webdriverio you are using?

**Comment by riccardoroasio** [comment]
Hi,

I'm uing firefox 41.0.2 , selenium 2.48.2 and webdriverio 3.4.0.

Tell me if you need more infos.

Best Regards,
Riccardo

2016-01-26 13:06 GMT+01:00 Christian Maniewski <notifications@github.com>:

**Comment by chmanie** [comment]
I added tests for manual initialisation and it all seems to work fine. Could you provide a minimal test case (the whole file, preferably using a gist)?

Thank you.

**Comment by riccardoroasio** [comment]
Can you please probide me an example? Maybe I'm doing something wrong....

Thanks

2016-01-27 9:01 GMT+01:00 Christian Maniewski <notifications@github.com>:

**Comment by riccardoroasio** [comment]
Here is the gist:

https://gist.github.com/riccardoroasio/2a2e9725bf1acc908753

Hope it will help!

Best Regards,
Riccardo Roasio

2016-01-27 9:12 GMT+01:00 Riccardo Roasio <riccardo.roasio@gmail.com>:

**Comment by chmanie** [comment]
This is a very minimal example (assumptions are that a selenium server is running and that you have the chrome driver installed on your system):

```
var webdriverio = require('webdriverio');
var wdajax = require('webdriverajax');
var assert = require('assert');

var client = webdriverio.remote({
  desiredCapabilities: {
    browserName: 'chrome'
  }
});

wdajax.init(client);

client
    .init()
    .url('https://www.google.com')
    .setupInterceptor()
    .execute(function checkSetup () {
        return window.__webdriverajax;
    }).then(function (ret) {
        assert.deepEqual(ret.value, { requests: [] });
    })
    .end();
```

**Comment by riccardoroasio** [comment]
Hi check your example but I think the error is caused by:

.getRequests()
.then(function(requests){console.log(requests);})

without these two lines all works but i I try to retrieve ajax
requests it crashes with:

RuntimeError: window.__webdriverajax is undefined

Hope it can help,


Best regards,

Riccardo



2016-01-27 9:30 GMT+01:00 Christian Maniewski <notifications@github.com>:

**Comment by chmanie** [comment]
Closing in favour of #3

**Comment by chmanie** [comment]
@riccardoroasio please check if version 1.1.0 works for you :)

**Comment by riccardoroasio** [comment]
Thanks a lot!
I will give it a try and let you know if it works for me.


Best Regards,
Riccardo Roasio

2016-02-05 10:33 GMT+01:00 Christian Maniewski <notifications@github.com>:

**Comment by riccardoroasio** [comment]
Hi,

I tested version 1.1.0 but it gives me this error:

Error: Could not find request with index undefined
    at execute(<Function>, ) - index.js:104:27
    at elementIdClick("2") - click.js:30:33

This is the code I'm using:

var webdriverio = require('webdriverio');
var wdajax = require('webdriverajax');

var fs = require('fs');



  var options = { desiredCapabilities: { browserName: 'firefox' } };
var client = webdriverio.remote(options);


 var i=0;

wdajax.init(client);

 function test(){
     i++;
     console.log("starting :"+i);
     var start = new Date().getTime();



client
    .init()
    .setViewportSize({width:1920,height:1080})
 // .setViewportSize({width:400,height:800},true)
    .url('https://www.rivenditorisisal.it/home?utm_source=alliumtechSARR')
    .setupInterceptor() // capture ajax calls
    .saveScreenshot('./snapshot1.png')

.waitForExist('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/div[1]/input',10000)

.setValue('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/div[1]/input','username')
    .saveScreenshot('./snapshot2.png')

.setValue('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/div[2]/input','password')
    .saveScreenshot('./snapshot3.png')

.click('//div[2]/div/header/div/div[3]/div/div/div[2]/div/form/input[5]')
  //  .pause(1000)
    .getRequests()
    .then(function(requests)
    {
      console.log("REQUESTS: "+JSON.stringify(requests));
    })
 .end()

Best Regards,
Riccardo Roasio

2016-02-05 10:37 GMT+01:00 Riccardo Roasio <riccardo.roasio@gmail.com>:

**Comment by chmanie** [comment]
The site you are testing doesn't make an XHR request (at least when you execute the exact test you described). You can assess that easily using the chrome/FF dev tools (enable the "preserve log" option).
