### ISSUE TITLE
no available function to read request data

### ISSUE THREAD

**Issue by jennliacl** [chmanie/webdriverajax#10]
Hi Cris,
Thanks for making this package, i'm currently trying to intercept my request payload, but i realized this tool only verifies detailed body on the response, not on the request. Can you give me some idea how I can do this? Thanks

**Comment by chmanie** [comment]
Hey Jennifer, you are right, indeed, currently you can just assess the headers and the body of the response. Let me look into that and come back to you.

**Comment by jennliacl** [comment]
Sure, thanks for the quick response!

**Comment by chmanie** [comment]
I'm about to add support for

- string
- json
- FormData
- ArrayBuffer (experimental)

request bodies. Will that cover your use case?

**Comment by rizzak** [comment]
Thank you, Christian!

**Comment by rizzak** [comment]
How I can get your new changes?

**Comment by chmanie** [comment]
Pushed v2.1.0 w/ request body support. Closing this now. Thank you for providing feedback @jennliacl, @rizzak 🌮
