### ISSUE TITLE
getRequests() not fetching all requests

### ISSUE THREAD

**Issue by mDomingues** [chmanie/webdriverajax#5]
Hi,

I'm using **getRequests()** to validate some requests with specific params but sometimes, promise does not grab what I want. 

Sample: 
```
        browser
        .setupInterceptor()
        .click(id)
        .pause(1000)
        .getRequests().then(function(requests){ // tests  }
```

Even with a larger pause, **requests** lacks.
Inspecting my front-end site, all requests are made quickly.  At a blink of an eye. 

Do you have any idea ?

**Comment by chmanie** [comment]
I'm sorry, without seeing the exact site you're testing (and the code you are using to test it) I can't make a guess here. You can join the [![gitter](https://badges.gitter.im/chmanie/webdriverajax.svg)](https://gitter.im/chmanie/webdriverajax?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) chat to see if we can work on that.

**Comment by michaelDomingues** [comment]
@chmanie thanks for your answer.
Now I'm getting those missing requests. A pause was the key. :)

**Comment by chmanie** [comment]
Great!
Closing this.
